include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - lib/generated_plugin_registrant.dart
    - "**/*.freezed.dart"

linter:
  rules:
    no_leading_underscores_for_local_identifiers: false
    prefer_single_quotes: true
    lines_longer_than_80_chars: true
    argument_type_not_assignable: false
    constant_identifier_names: false
    avoid_print: true
    always_put_required_named_parameters_first: true,
    flutter_style_todos: false
    always_specify_types: true
