name: quatrokantos
description: Desktop Site Manager

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  archive: ^3.3.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_storage: ^2.1.1
  msix: ^3.9.1
  outline_gradient_button: ^2.0.1+1
  path_provider: ^2.0.14
  platform: ^3.1.0
  process_run: ^0.12.5+2
  system_info: ^1.0.1
  system_tray: ^2.0.2
  tint: ^2.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/svg/
    - assets/scripts/

msix_config:
  display_name: Thiftshop App
  publisher: 53614Goldcoders.ThriftshopApp
  publisher_display_name: Goldcoders
  identity_name: 53614Goldcoders.ThriftshopApp
  msix_version: 1.0.0.0
  logo_path: 'C:\Users\uriah\Code\quatrokantos\assets\images\app.png'
  capabilities: "internetClientServer,"
  icons_background_color: "#00275B"
  execution_alias: "thriftshop"
  store: true
