# This is a development snapcraft file, no version is specified. Uncomment the line below to build a snap.
#version: "0.1.0"
name: quatrokantos
summary: Thriftshop Site Manager
description: |
  Offline First Site Manager for Different Cloud Services like Netlify, Vercel etc.

confinement: strict
base: core18
grade: stable
icon: snap/gui/app.png

apps:
  quatrokantos:
    command: desktop-launch quatrokantos
    extensions: [flutter-beta]
    plugs:
      - network
      - desktop
      - home

parts:
  quatrokantos:
    source: https://github.com/goldcoders/quatrokantos.git
    plugin: flutter
    flutter-target: lib/main.dart